name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  location: ^5.0.3
  mapbox_maps_flutter: ^2.9.0
  mobile_scanner: ^6.0.10
  permission_handler: ^11.3.0
  provider: ^6.1.4
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.3
  socket_io_client: ^2.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
